# Required
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

# Build documentation in the doc/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

conda:
    environment: environment_doc.yml

python:
  install:
    - method: pip
      path: .
